# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_EXYNOS) += \
	exynos5433-tm2.dtb \
	exynos5433-tm2e.dtb \
	exynos7-espresso.dtb \
	exynos7870-smdk7870.dtb \
	exynos7870-universal7870.dtb \
	exynos7870-universal7870_rev01.dtb \
	exynos7870-on7xelte_swa_open_02.dtb \
	exynos7870-on7xelte_swa_open_01.dtb \
	exynos7870-on7xelte_swa_open_00.dtb

always := $(dtb-y)
clean-files := *.dtb
